name: CI - Flask App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r flask-app/requirements.txt
    
    - name: Run unit tests
      run: |
        pytest flask-app/tests


    - name: Run Flask app in background
      run: |
        nohup python flask-app/app.py &

    - name: Run tests (example)
      run: |
        # Make sure the Flask app is running before hitting it with tests
        curl --silent --fail http://localhost:5000 || exit 1
        # Here you can replace the curl command with actual test scripts later
